//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_InteractUI;
        
        private static SteamVR_Action_Boolean p_default_Teleport;
        
        private static SteamVR_Action_Boolean p_default_GrabPinch;
        
        private static SteamVR_Action_Boolean p_default_GrabGrip;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Single p_default_Squeeze;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Vector2 p_default_TrackpadAxis;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        private static SteamVR_Action_Vector2 p_platformer_Move;
        
        private static SteamVR_Action_Boolean p_platformer_Jump;
        
        private static SteamVR_Action_Vector2 p_buggy_Steering;
        
        private static SteamVR_Action_Single p_buggy_Throttle;
        
        private static SteamVR_Action_Boolean p_buggy_Brake;
        
        private static SteamVR_Action_Boolean p_buggy_Reset;
        
        private static SteamVR_Action_Pose p_mixedreality_ExternalCamera;
        
        private static SteamVR_Action_Vector2 p_vRControlActionSet_TrackpadAxis;
        
        private static SteamVR_Action_Boolean p_vRControlActionSet_TrackpadButton;
        
        private static SteamVR_Action_Single p_vRControlActionSet_TriggerAxis;
        
        private static SteamVR_Action_Boolean p_vRControlActionSet_TriggerButton;
        
        private static SteamVR_Action_Boolean p_vRControlActionSet_SideButton;
        
        private static SteamVR_Action_Boolean p_vRControlActionSet_MenuButton;
        
        private static SteamVR_Action_Boolean p_vRControlActionSet_TrackpadDPadUp;
        
        private static SteamVR_Action_Boolean p_vRControlActionSet_TrackpadDPadDown;
        
        private static SteamVR_Action_Boolean p_vRControlActionSet_TrackpadDPadRight;
        
        private static SteamVR_Action_Boolean p_vRControlActionSet_TrackpadDPadLeft;
        
        private static SteamVR_Action_Pose p_vRControlActionSet_Pose;
        
        private static SteamVR_Action_Boolean p_vRControlActionSet_HeadsetOnHead;
        
        private static SteamVR_Action_Skeleton p_vRControlActionSet_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_vRControlActionSet_SkeletonRightHand;
        
        private static SteamVR_Action_Vibration p_vRControlActionSet_Haptic;
        
        public static SteamVR_Action_Boolean default_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_default_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Teleport
        {
            get
            {
                return SteamVR_Actions.p_default_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabPinch
        {
            get
            {
                return SteamVR_Actions.p_default_GrabPinch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_GrabGrip
        {
            get
            {
                return SteamVR_Actions.p_default_GrabGrip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Single default_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_TrackpadAxis
        {
            get
            {
                return SteamVR_Actions.p_default_TrackpadAxis.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        public static SteamVR_Action_Vector2 platformer_Move
        {
            get
            {
                return SteamVR_Actions.p_platformer_Move.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean platformer_Jump
        {
            get
            {
                return SteamVR_Actions.p_platformer_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 buggy_Steering
        {
            get
            {
                return SteamVR_Actions.p_buggy_Steering.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single buggy_Throttle
        {
            get
            {
                return SteamVR_Actions.p_buggy_Throttle.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Brake
        {
            get
            {
                return SteamVR_Actions.p_buggy_Brake.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean buggy_Reset
        {
            get
            {
                return SteamVR_Actions.p_buggy_Reset.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose mixedreality_ExternalCamera
        {
            get
            {
                return SteamVR_Actions.p_mixedreality_ExternalCamera.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vector2 vRControlActionSet_TrackpadAxis
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_TrackpadAxis.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean vRControlActionSet_TrackpadButton
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_TrackpadButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single vRControlActionSet_TriggerAxis
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_TriggerAxis.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean vRControlActionSet_TriggerButton
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_TriggerButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRControlActionSet_SideButton
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_SideButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRControlActionSet_MenuButton
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_MenuButton.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRControlActionSet_TrackpadDPadUp
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_TrackpadDPadUp.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRControlActionSet_TrackpadDPadDown
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_TrackpadDPadDown.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRControlActionSet_TrackpadDPadRight
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_TrackpadDPadRight.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRControlActionSet_TrackpadDPadLeft
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_TrackpadDPadLeft.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose vRControlActionSet_Pose
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean vRControlActionSet_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Skeleton vRControlActionSet_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton vRControlActionSet_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vibration vRControlActionSet_Haptic
        {
            get
            {
                return SteamVR_Actions.p_vRControlActionSet_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TrackpadAxis,
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.vRControlActionSet_TrackpadAxis,
                    SteamVR_Actions.vRControlActionSet_TrackpadButton,
                    SteamVR_Actions.vRControlActionSet_TriggerAxis,
                    SteamVR_Actions.vRControlActionSet_TriggerButton,
                    SteamVR_Actions.vRControlActionSet_SideButton,
                    SteamVR_Actions.vRControlActionSet_MenuButton,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadUp,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadDown,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadRight,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadLeft,
                    SteamVR_Actions.vRControlActionSet_Pose,
                    SteamVR_Actions.vRControlActionSet_HeadsetOnHead,
                    SteamVR_Actions.vRControlActionSet_SkeletonLeftHand,
                    SteamVR_Actions.vRControlActionSet_SkeletonRightHand,
                    SteamVR_Actions.vRControlActionSet_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TrackpadAxis,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.vRControlActionSet_TrackpadAxis,
                    SteamVR_Actions.vRControlActionSet_TrackpadButton,
                    SteamVR_Actions.vRControlActionSet_TriggerAxis,
                    SteamVR_Actions.vRControlActionSet_TriggerButton,
                    SteamVR_Actions.vRControlActionSet_SideButton,
                    SteamVR_Actions.vRControlActionSet_MenuButton,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadUp,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadDown,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadRight,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadLeft,
                    SteamVR_Actions.vRControlActionSet_Pose,
                    SteamVR_Actions.vRControlActionSet_HeadsetOnHead,
                    SteamVR_Actions.vRControlActionSet_SkeletonLeftHand,
                    SteamVR_Actions.vRControlActionSet_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.vRControlActionSet_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic,
                    SteamVR_Actions.vRControlActionSet_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.mixedreality_ExternalCamera,
                    SteamVR_Actions.vRControlActionSet_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.vRControlActionSet_TrackpadButton,
                    SteamVR_Actions.vRControlActionSet_TriggerButton,
                    SteamVR_Actions.vRControlActionSet_SideButton,
                    SteamVR_Actions.vRControlActionSet_MenuButton,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadUp,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadDown,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadRight,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadLeft,
                    SteamVR_Actions.vRControlActionSet_HeadsetOnHead};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.vRControlActionSet_TriggerAxis};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_TrackpadAxis,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.vRControlActionSet_TrackpadAxis};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.vRControlActionSet_SkeletonLeftHand,
                    SteamVR_Actions.vRControlActionSet_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_InteractUI,
                    SteamVR_Actions.default_Teleport,
                    SteamVR_Actions.default_GrabPinch,
                    SteamVR_Actions.default_GrabGrip,
                    SteamVR_Actions.default_Squeeze,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TrackpadAxis,
                    SteamVR_Actions.platformer_Move,
                    SteamVR_Actions.platformer_Jump,
                    SteamVR_Actions.buggy_Steering,
                    SteamVR_Actions.buggy_Throttle,
                    SteamVR_Actions.buggy_Brake,
                    SteamVR_Actions.buggy_Reset,
                    SteamVR_Actions.vRControlActionSet_TrackpadAxis,
                    SteamVR_Actions.vRControlActionSet_TrackpadButton,
                    SteamVR_Actions.vRControlActionSet_TriggerAxis,
                    SteamVR_Actions.vRControlActionSet_TriggerButton,
                    SteamVR_Actions.vRControlActionSet_SideButton,
                    SteamVR_Actions.vRControlActionSet_MenuButton,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadUp,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadDown,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadRight,
                    SteamVR_Actions.vRControlActionSet_TrackpadDPadLeft,
                    SteamVR_Actions.vRControlActionSet_HeadsetOnHead};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/InteractUI")));
            SteamVR_Actions.p_default_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Teleport")));
            SteamVR_Actions.p_default_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabPinch")));
            SteamVR_Actions.p_default_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/GrabGrip")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Squeeze")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_TrackpadAxis = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/TrackpadAxis")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
            SteamVR_Actions.p_platformer_Move = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/platformer/in/Move")));
            SteamVR_Actions.p_platformer_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/platformer/in/Jump")));
            SteamVR_Actions.p_buggy_Steering = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/buggy/in/Steering")));
            SteamVR_Actions.p_buggy_Throttle = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/buggy/in/Throttle")));
            SteamVR_Actions.p_buggy_Brake = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Brake")));
            SteamVR_Actions.p_buggy_Reset = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/buggy/in/Reset")));
            SteamVR_Actions.p_mixedreality_ExternalCamera = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/mixedreality/in/ExternalCamera")));
            SteamVR_Actions.p_vRControlActionSet_TrackpadAxis = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/VRControlActionSet/in/TrackpadAxis")));
            SteamVR_Actions.p_vRControlActionSet_TrackpadButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRControlActionSet/in/TrackpadButton")));
            SteamVR_Actions.p_vRControlActionSet_TriggerAxis = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/VRControlActionSet/in/TriggerAxis")));
            SteamVR_Actions.p_vRControlActionSet_TriggerButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRControlActionSet/in/TriggerButton")));
            SteamVR_Actions.p_vRControlActionSet_SideButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRControlActionSet/in/SideButton")));
            SteamVR_Actions.p_vRControlActionSet_MenuButton = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRControlActionSet/in/MenuButton")));
            SteamVR_Actions.p_vRControlActionSet_TrackpadDPadUp = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRControlActionSet/in/TrackpadDPadUp")));
            SteamVR_Actions.p_vRControlActionSet_TrackpadDPadDown = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRControlActionSet/in/TrackpadDPadDown")));
            SteamVR_Actions.p_vRControlActionSet_TrackpadDPadRight = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRControlActionSet/in/TrackpadDPadRight")));
            SteamVR_Actions.p_vRControlActionSet_TrackpadDPadLeft = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRControlActionSet/in/TrackpadDPadLeft")));
            SteamVR_Actions.p_vRControlActionSet_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/VRControlActionSet/in/Pose")));
            SteamVR_Actions.p_vRControlActionSet_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRControlActionSet/in/HeadsetOnHead")));
            SteamVR_Actions.p_vRControlActionSet_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/VRControlActionSet/in/SkeletonLeftHand")));
            SteamVR_Actions.p_vRControlActionSet_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/VRControlActionSet/in/SkeletonRightHand")));
            SteamVR_Actions.p_vRControlActionSet_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/VRControlActionSet/out/Haptic")));
        }
    }
}
