//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRControlActionSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 TrackpadAxis
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_TrackpadAxis;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadButton
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_TrackpadButton;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerAxis
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_TriggerAxis;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerButton
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_TriggerButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SideButton
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_SideButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuButton
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_MenuButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadDPadUp
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_TrackpadDPadUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadDPadDown
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_TrackpadDPadDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadDPadRight
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_TrackpadDPadRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadDPadLeft
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_TrackpadDPadLeft;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.vRControlActionSet_Haptic;
            }
        }
    }
}
